services:
  sql2025:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql2025
    hostname: sql2025
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Poty1217566!"
    ports:
      - "1433:1433"
    volumes:
      - ${HOME}/docker/sql2025/data:/var/opt/mssql/data
      - ${HOME}/docker/sql2025/log:/var/opt/mssql/log
      - ${HOME}/docker/sql2025/secrets:/var/opt/mssql/secrets
    restart: always
